We generated phylogenetic trees based on the distance matrices of i) the first 
principle component ii) the first five principal components which had different 
branch lengths but overall similar topology depending on whether we used the 
first or the first five principal components. 

It is worth noting that both rooted and unrooted trees can be generated by this
method despite us only showing rooted trees. Moreover, other principal
components could have been used but we preferred to use the ones that gave a 
more parsimonious tree.


\todo{Any effects from using different tools for assembly and bluntification?}

** RSV
When using the first five principal components we generated a tree shown in 
[[fig:hh20_all_pcs]] that was more parsimonious.

When using the first principal component we got a tree that seemed to visually
depict a linear relation between the samples in two clades shown in
[[fig:hh20_first_pc]].

Even though the trees from the first or the first five principal components 
have a similar overall topology they have different branch lengths. 
We attribute the maximized branch length in [[fig:SARS_CoV_2_first_pc]] and 
[[fig:hh20_first_pc]] to the
first principal component being the one that differentiates the data the most.
It seems that [[fig:SARS_CoV_2_all_pcs]] and [[fig:hh20_all_pcs]] gave a more realistic
estimation of evolutionary distance.

** SARS-CoV-2
The differentiation was in accordance with the mutation rates we set when 
\todo{are the mutation rates in the tree exactly in accordance with what we set?}
generating the reads where samples 1 and 2 were closer to the reference and each
other than the sample that allowed for the generation of the dendrogram as shown 
in [[fig:SARS_CoV_2_first_pc]] and [[fig:SARS_CoV_2_all_pcs]].

#+LATEX: \begin{landscape}
#+CAPTION[RSV PC1 cladogram]: A rooted cladogram of RSV generated through neighbour joining of a distance matrix of the first five principal components from a principal component analysis of each of the sample’s coverage vectors.
#+ATTR_LATEX: :scale 1.0 :float multicolumn
#+NAME: fig:hh20_all_pcs
file:../Figures/RSV/HH20_all_principal_components_nj_tree.png

#+CAPTION[RSV PC1 to PC5 cladogram]: A rooted cladogram of RSV generated through neighbour joining of a distance matrix of the first principal component from a principal component analysis of each of the sample’s coverage vectors.
#+ATTR_LATEX: :scale 1.0 :float multicolumn
#+NAME: fig:hh20_first_pc
file:../Figures/RSV/HH20_first_principal_component_nj_tree.png

#+CAPTION[SARS-CoV-2 PC1 cladogram]: A cladogram generated through neighbour joining  of a distance matrix of the first five  principal components of the coverage vector.
#+ATTR_LATEX: :scale 1.0 :float multicolumn
#+NAME: fig:SARS_CoV_2_first_pc
file:../Figures/SARS_CoV_2/SARS_CoV_2_first_principal_component_nj_tree.png

#+LATEX: \begin{landscape}
#+CAPTION[SARS-CoV-2 PC1 to PC5 cladogram]: A cladogram generated through neighbour joining  of a distance matrix of the first principal component of the coverage vector.
#+ATTR_LATEX: :scale 1.0 :float multicolumn
#+NAME: fig:SARS_CoV_2_all_pcs
file:../Figures/SARS_CoV_2/SARS_CoV_2_all_principal_components_nj_tree.png
#+LATEX: \end{landscape}
